#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env.production.local"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

info()  { echo -e "${GREEN}[deploy]${NC} $*"; }
warn()  { echo -e "${YELLOW}[deploy]${NC} $*"; }
error() { echo -e "${RED}[deploy]${NC} $*" >&2; }
die()   { error "$@"; exit 1; }

# ── Helpers ───────────────────────────────────────────────────────────
random_hex() { openssl rand -hex 32; }

load_env() {
  if [[ ! -f "$ENV_FILE" ]]; then
    die "Missing $ENV_FILE — run '$0 generate-secrets' first or copy .env.production.local.example"
  fi
  set -a
  # shellcheck source=/dev/null
  source "$ENV_FILE"
  set +a
}

require_var() {
  local name="$1"
  if [[ -z "${!name:-}" ]]; then
    die "Required secret $name is empty in $ENV_FILE"
  fi
}

# ── Generate secrets ─────────────────────────────────────────────────
generate_secrets() {
  info "Generating fresh secrets..."

  # Preserve persistent values if .env.production.local already exists
  local existing_telegram_bot_token=""
  local existing_telegram_bot_username=""
  local existing_ev_api_key=""
  if [[ -f "$ENV_FILE" ]]; then
    existing_telegram_bot_token=$(grep -E '^TELEGRAM_BOT_TOKEN=' "$ENV_FILE" | cut -d= -f2- || true)
    existing_telegram_bot_username=$(grep -E '^TELEGRAM_BOT_USERNAME=' "$ENV_FILE" | cut -d= -f2- || true)
    existing_ev_api_key=$(grep -E '^EV_API_KEY=' "$ENV_FILE" | cut -d= -f2- || true)
    warn "Preserving existing TELEGRAM_BOT_TOKEN, TELEGRAM_BOT_USERNAME, EV_API_KEY"
  fi

  local ticket_secret
  local internal_api_key
  local sealing_key
  local session_secret
  ticket_secret=$(random_hex)
  internal_api_key=$(random_hex)
  sealing_key=$(random_hex)
  session_secret=$(random_hex)

  cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy.sh generate-secrets on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Do NOT commit this file

# Shared between CF Worker (api) and Evervault Enclave
TICKET_SIGNING_SECRET=${ticket_secret}
INTERNAL_API_KEY=${internal_api_key}

# Enclave only
SEALING_KEY=${sealing_key}

# CF Worker (api) only
SESSION_SIGNING_SECRET=${session_secret}
EV_API_KEY="${existing_ev_api_key}"
TELEGRAM_BOT_TOKEN="${existing_telegram_bot_token}"
TELEGRAM_BOT_USERNAME="${existing_telegram_bot_username}"
EOF

  chmod 600 "$ENV_FILE"
  info "Written $ENV_FILE with fresh random secrets"
  if [[ -z "$existing_ev_api_key" ]]; then
    warn "EV_API_KEY is empty — edit $ENV_FILE and fill it in before deploying"
  fi
  if [[ -z "$existing_telegram_bot_token" ]]; then
    warn "TELEGRAM_BOT_TOKEN is empty — edit $ENV_FILE and fill it in before deploying"
  fi
}

# ── Service: enclave ──────────────────────────────────────────────────
deploy_enclave() {
  info "Deploying enclave..."
  load_env
  require_var EV_API_KEY
  require_var TICKET_SIGNING_SECRET
  require_var INTERNAL_API_KEY
  require_var SEALING_KEY

  # ev CLI needs these in the environment
  export EV_API_KEY
  export EV_APP_UUID="app_366535fdf2b7"

  # Build EIF (Docker context is the enclave/ directory)
  info "Building enclave image..."
  ev enclave build -v --output "$ROOT_DIR" -c "$ROOT_DIR/infra/enclave.toml" "$ROOT_DIR/enclave"

  # Deploy the built EIF
  info "Deploying enclave image..."
  ev enclave deploy --eif-path "$ROOT_DIR/enclave.eif" -c "$ROOT_DIR/infra/enclave.toml"

  # Set env vars (secrets)
  info "Setting enclave environment variables..."
  local enclave_secrets=(TICKET_SIGNING_SECRET INTERNAL_API_KEY SEALING_KEY)
  for var in "${enclave_secrets[@]}"; do
    info "  Setting $var..."
    ev enclave env add \
      -c "$ROOT_DIR/infra/enclave.toml" \
      --key "$var" \
      --value "${!var}" \
      --secret
  done

  # Restart to pick up new env vars
  info "Restarting enclave..."
  ev enclave restart -c "$ROOT_DIR/infra/enclave.toml"

  warn "Remember to update PCR values in infra/enclave.toml if the image changed."
  warn "Run: ev enclave describe ./enclave.eif --json | jq '.attestation'"
  info "Enclave deploy complete!"
}

# ── Service: api ──────────────────────────────────────────────────────
deploy_api() {
  info "Deploying API (Cloudflare Worker)..."
  load_env
  require_var INTERNAL_API_KEY
  require_var TICKET_SIGNING_SECRET
  require_var SESSION_SIGNING_SECRET
  require_var EV_API_KEY

  # Set secrets on CF Worker
  info "Setting Worker secrets..."
  local api_secrets=(INTERNAL_API_KEY TICKET_SIGNING_SECRET SESSION_SIGNING_SECRET EV_API_KEY TELEGRAM_BOT_TOKEN TELEGRAM_BOT_USERNAME)
  for var in "${api_secrets[@]}"; do
    # Skip optional secrets if empty
    if [[ -z "${!var:-}" ]]; then
      warn "  Skipping $var (empty)"
      continue
    fi
    info "  Setting $var..."
    echo "${!var}" | wrangler secret put "$var" --env production --config "$ROOT_DIR/api/wrangler.toml"
  done

  # Deploy worker
  info "Deploying worker..."
  wrangler deploy --env production --config "$ROOT_DIR/api/wrangler.toml"

  info "API deploy complete!"
}

# ── Service: web ──────────────────────────────────────────────────────
deploy_web() {
  info "Deploying web (Cloudflare Pages)..."

  info "Building web..."
  pnpm --filter @clw-cash/web build

  info "Publishing to Cloudflare Pages..."
  wrangler pages deploy "$ROOT_DIR/web/dist" --project-name clw-cash-web

  info "Web deploy complete!"
}

# ── Service: landing ──────────────────────────────────────────────────
deploy_landing() {
  info "Deploying landing page (Cloudflare Pages)..."

  wrangler pages deploy "$ROOT_DIR/landing-page" --project-name claw-cash-landing-page

  info "Landing page deploy complete!"
}

# ── Service: cli ──────────────────────────────────────────────────────
deploy_cli() {
  info "Publishing CLI to npm..."

  info "Building CLI..."
  pnpm --filter clw-cash build

  info "Publishing..."
  (cd "$ROOT_DIR/cli" && npm publish)

  info "CLI publish complete!"
}

# ── Orchestration ─────────────────────────────────────────────────────
deploy_all() {
  deploy_enclave
  deploy_api
  deploy_web
  deploy_landing
  deploy_cli
  info "All services deployed!"
}

# ── Main ──────────────────────────────────────────────────────────────
usage() {
  cat <<EOF
Usage: $(basename "$0") <command>

Commands:
  generate-secrets  Generate fresh random secrets in .env.production.local
  enclave           Build, deploy, and configure Evervault Enclave
  api               Deploy Cloudflare Worker with secrets
  web               Build and deploy web app to Cloudflare Pages
  landing           Deploy landing page to Cloudflare Pages
  cli               Build and publish CLI to npm
  all               Deploy all services in order
EOF
  exit 1
}

if [[ $# -lt 1 ]]; then
  usage
fi

case "$1" in
  generate-secrets) generate_secrets ;;
  enclave) deploy_enclave ;;
  api)     deploy_api ;;
  web)     deploy_web ;;
  landing) deploy_landing ;;
  cli)     deploy_cli ;;
  all)     deploy_all ;;
  *)       error "Unknown command: $1"; usage ;;
esac
